backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: '[skip ci] Create {{collection}} “{{slug}}”'
    update: '[skip ci] Update {{collection}} “{{slug}}”'
    delete: '[skip ci] Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "evangelios"
    label: "Evangelios"
    folder: "src/evangelios"
    slug: "{{year}}-{{month}}-{{day}}"
    create: true
    fields: 
      - {label: "Cita", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime", time_format: false}
      - {label: "Url del podcast", name: "link", widget: "string", required: false}
      - {label: "Evangelio", name: "body", widget: "markdown"}
